// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPSachIFXWYhcdxWlWh2iD9Jhj-EH8p2s',
    appId: '1:985942742649:web:99dbf3da6a7ac34bbd66a8',
    messagingSenderId: '985942742649',
    projectId: 'ptupapers-a7631',
    authDomain: 'ptupapers-a7631.firebaseapp.com',
    storageBucket: 'ptupapers-a7631.appspot.com',
    measurementId: 'G-XQJ3PJL6KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnR9AXSfSAsQQ_2D_sosDfNhHmhYYuVr8',
    appId: '1:985942742649:android:9579585149a3051ebd66a8',
    messagingSenderId: '985942742649',
    projectId: 'ptupapers-a7631',
    storageBucket: 'ptupapers-a7631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSkFOUkqnHnquBvIIXaectmkXmtzupsg',
    appId: '1:985942742649:ios:cb0adc252a74fcb7bd66a8',
    messagingSenderId: '985942742649',
    projectId: 'ptupapers-a7631',
    storageBucket: 'ptupapers-a7631.appspot.com',
    iosClientId: '985942742649-28etogbadobnr66i8utj2u7gqa0s3g6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptuepapers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvSkFOUkqnHnquBvIIXaectmkXmtzupsg',
    appId: '1:985942742649:ios:cb0adc252a74fcb7bd66a8',
    messagingSenderId: '985942742649',
    projectId: 'ptupapers-a7631',
    storageBucket: 'ptupapers-a7631.appspot.com',
    iosClientId: '985942742649-28etogbadobnr66i8utj2u7gqa0s3g6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ptuepapers',
  );
}
